---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: adminapplication
 labels:
  app: adminapplication
spec:
 replicas: 1
 selector:
  matchLabels:
   app: adminapplication
 template:
  metadata: 
   labels:
    app: adminapplication
  spec:
   containers:
   - name: adminapplication
     image: harinathdockerid/v5adminapp:tagversion
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: adminapp
spec:
  type: LoadBalancer
  selector:
    app: adminapplication
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
